main: net.mcpandemic.core.Main
version: 1.0
name: mcpandemic
api-version: 1.16
depend: [ProtocolLib, LibsDisguises]
softdepend: [Multiverse-Core]
commands:
  arena:
  vote:
  infectedKits:
    aliases: [kit, kits]
  setrank:
    description: Set a players rank.
    aliases: [ sr ]
  setinfectedrank:
    description: Set a players infected rank.
    aliases: [ sir ]
  setprestige:
    description: Set a players prestige rank.
    aliases: [ sp ]
  rankup:
    description: Rankup with Rankpoints!
    aliases: [ ru ]