main: com.infected.ranks.Main
version: 1.0
name: InfectedRanks
commands:
  setrank:
    description: Set a players rank.
    aliases: [sr]
  setinfectedrank:
    description: Set a players infected rank.
    aliases: [sir]
  setprestige:
    description: Set a players prestige rank.
    aliases: [sp]